### ISSUE TITLE
ResolutionImpossible error on pip install

### ISSUE THREAD

**Issue by brahambence** [FedericoDiMarzo/BeatlesChordsMarkovChain#1]
Hi, thank you for publishing this package!

I'm not advanced in python, so forgive me if this is an obvious thing to solve, but I get an error when installing this package with pip:

```
ERROR: Cannot install beatles-chords-markov-chain==0.0.20, beatles-chords-markov-chain==0.0.21, beatles-chords-markov-chain==0.0.22 and beatles-chords-markov-chain==0.0.23 because these package versions have conflicting dependencies.

The conflict is caused by:
    beatles-chords-markov-chain 0.0.23 depends on scipy==1.6.3
    beatles-chords-markov-chain 0.0.22 depends on scipy==1.6.3
    beatles-chords-markov-chain 0.0.21 depends on scipy==1.6.3
    beatles-chords-markov-chain 0.0.20 depends on scipy==1.6.3
```

Environment: Windows 10, python 3.10

Is there an easy fix for this that I can make in my own environment, or should I look into what's causing this in the package and try to solve with a PR? Thanks for any help!

**Comment by FedericoDiMarzo** [comment]
Hi, I will check soon, maybe there are some problems in the distribution.

In the meantime, I suggest you to clone the repo, and deal with the dependencies manually, starting from the requirement.txt you can find them all.

**Comment by brahambence** [comment]
All right, thanks!

**Comment by FedericoDiMarzo** [comment]
Hi, I tried to solve the dependency issues, but they seem related to the lack of compatibility with python3.10. Even relaxing the dependencies constraints I couldn't reach to make it work with python3.10. Unfortunately, I don't have much time to dive into these compatibilities problems at the moment.

I can suggest you try using python3.9 instead.
Have a nice day!

**Comment by brahambence** [comment]
Thanks, I will do that!
